language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t seasickturtle/learn-docker-kub-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true seasickturtle/learn-docker-kub-aws yarn test
